<?php

use PHPUnit\Framework\TestCase;
use Surreal\classes\exceptions\SurrealException;
use Surreal\SurrealHTTP;

final class BasicTest extends TestCase
{
    private static SurrealHTTP $http_db;

    public static function setUpBeforeClass(): void
    {
        self::$http_db = new SurrealHTTP(
            host: "http://localhost:8000",
            target: ["namespace" => "test", "database" => "test"]
        );

        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws SurrealException
     */
    public function testStatus(): void
    {
        $status = self::$http_db->status();

        $this->assertIsInt($status);
        $this->assertEquals(200, $status);
    }

    /**
     * @throws SurrealException
     */
    public function testHealth(): void
    {
        $health = self::$http_db->health();

        $this->assertIsInt($health);
        $this->assertEquals(200, $health);
    }

    /**
     * @throws Exception
     */
    public function testVersion(): void
    {
        $version = self::$http_db->version();

        $this->assertIsString($version);
        $this->assertStringStartsWith("surrealdb-", $version);
    }

    public static function tearDownAfterClass(): void
    {
        self::$http_db->close();
        parent::tearDownAfterClass();
    }
}