<?php

use PHPUnit\Framework\TestCase;
use Surreal\SurrealHTTP;

class ImportTest extends TestCase
{
    private static SurrealHTTP $http_db;

    public static function setUpBeforeClass(): void
    {
        self::$http_db = new SurrealHTTP(
            host: "http://localhost:8000",
            target: ["namespace" => "test", "database" => "test"]
        );

        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws Exception
     */
    public function testImport(): void
    {
        $file = __DIR__ . "/assets/import.surql";
        $file = file_get_contents($file);

        $result = self::$http_db->import($file, "root", "root");

        $this->assertIsArray($result);
    }

    public static function tearDownAfterClass(): void
    {
        self::$http_db->close();
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}