<?php

use PHPUnit\Framework\TestCase;
use Surreal\SurrealHTTP;

class SigninTest extends TestCase
{
    private static SurrealHTTP $http_db;

    public static function setUpBeforeClass(): void
    {
        self::$http_db = new SurrealHTTP(
            host: "http://localhost:8000",
            target: ["namespace" => "test", "database" => "test"]
        );

        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws Exception
     */
    public function testSigninRoot(): void {

        $token = self::$http_db->signin([
            "user" => "beaurt",
            "pass" => "123456"
        ]);

        $this->assertIsString($token);
    }

    /**
     *
     * @throws Exception
     */
    public function testSigninDatabase(): void
    {
        $token = self::$http_db->signin([
            "user" => "beaudb",
            "pass" => "123456",
            "ns" => "test",
            "db" => "test"
        ]);

        $this->assertIsString($token);
    }

    /**
     * @throws Exception
     */
    public function testSigninScope(): void
    {
        $token = self::$http_db->signin([
            "user" => "beau",
            "pass" => "123456",
            "ns" => "test",
            "db" => "test",
            "sc" => "user"
        ]);

        $this->assertIsString($token);
    }

    public static function tearDownAfterClass(): void
    {
        self::$http_db->invalidate();

        // last check to make sure the token is invalidated
        $token = self::$http_db->getToken();
        self::assertNull($token, "Token is not invalidated");

        self::$http_db->close();
        parent::tearDownAfterClass();
    }
}