<?php

namespace protocol\http;

use PHPUnit\Framework\TestCase;
use Surreal\SurrealHTTP;
use Surreal\SurrealWebsocket;

class AuthTest extends TestCase
{
    private static SurrealHTTP $db;

    public static function setUpBeforeClass(): void
    {
        self::$db = new SurrealHTTP(
            host: "http://localhost:8000",
            target: ["namespace" => "test", "database" => "test"]
        );

        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws \Exception
     */
    public function testSignUp(): void
    {
        $token = self::$db->signup([
            "user" => "beau",
            "pass" => "123456",
            "ns" => "test",
            "db" => "test"
        ]);

        self::assertIsString($token);
    }

    /**
     * @throws \Exception
     */
    public function testSignIn(): void
    {
        $token = self::$db->signin([
            "user" => "beau",
            "pass" => "123456",
            "ns" => "test",
            "db" => "test"
        ]);

        self::assertIsString($token);
    }

    public static function tearDownAfterClass(): void
    {
        self::$db->close();

        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}