<?php

namespace protocol\http;

use PHPUnit\Framework\TestCase;
use Surreal\SurrealWebsocket;

class AuthTest extends TestCase
{
    private static SurrealWebsocket $db;

    public static function setUpBeforeClass(): void
    {
        self::$db = new SurrealWebsocket(
            host: "http://localhost:8000",
            target: ["namespace" => "test", "database" => "test"]
        );

        self::assertTrue(self::$db->isConnected());

        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    public static function testSignUp(): void
    {
        self::$db->signup([
            "user" => "beau",
            "pass" => "123456",
            "ns" => "test",
            "db" => "test"
        ]);
    }

    public static function testSignIn(): void
    {
        self::$db->signin([
            "user" => "beau",
            "pass" => "123456",
            "ns" => "test",
            "db" => "test"
        ]);
    }

    public static function tearDownAfterClass(): void
    {
        self::$db->close();

        $connected = self::$db->isConnected();
        self::assertFalse($connected);

        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}