<?php

namespace protocol\http;

use Exception;
use PHPUnit\Framework\TestCase;
use Surreal\classes\exceptions\SurrealException;
use Surreal\SurrealHTTP;

final class BasicTest extends TestCase
{
    private static SurrealHTTP $db;

    public static function setUpBeforeClass(): void
    {
        self::$db = new SurrealHTTP(
            host: "http://localhost:8000",
            target: ["namespace" => "test", "database" => "test"]
        );

        self::assertEquals("http://localhost:8000", self::$db->getHost());

        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws SurrealException
     */
    public function testStatus(): void
    {
        $status = self::$db->status();

        $this->assertIsInt($status);
        $this->assertEquals(200, $status);
    }

    /**
     * @throws SurrealException
     */
    public function testHealth(): void
    {
        $health = self::$db->health();

        $this->assertIsInt($health);
        $this->assertEquals(200, $health);
    }

    /**
     * @throws Exception
     */
    public function testVersion(): void
    {
        $version = self::$db->version();

        $this->assertIsString($version);
        $this->assertStringStartsWith("surrealdb-", $version);
    }

    public function testTimeout(): void
    {
        self::$db->setTimeout(10);
        $timeout = self::$db->getTimeout();

        var_dump($timeout);

        $this->assertEquals(10, $timeout);

        self::$db->setTimeout(5);
        $this->assertEquals(5, self::$db->getTimeout());

        self::$db->setTimeout(1);
        $this->assertEquals(1, self::$db->getTimeout());
    }

    public function testToken(): void
    {
        self::$db->setToken("sometoken");
        $token = self::$db->getToken();

        $this->assertEquals("sometoken", $token);

        self::$db->setToken(null);
        $this->assertNull(self::$db->getToken());
    }

    public static function tearDownAfterClass(): void
    {
        self::$db->close();
        parent::tearDownAfterClass();
    }
}