<?php

namespace protocol\http;

use Exception;
use PHPUnit\Framework\TestCase;
use Surreal\Core\Client\SurrealHTTP;
use Surreal\Exceptions\AuthException;
use Surreal\Exceptions\SurrealException;

class ImportTest extends TestCase
{
    private static SurrealHTTP $db;

    public static function setUpBeforeClass(): void
    {
        self::$db = new SurrealHTTP(
            host: "http://localhost:8000",
            target: ["namespace" => "test", "database" => "test"]
        );

        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws Exception
     */
    public function testImport(): void
    {
        $file = __DIR__ . "/../../assets/import.surql";
        $file = file_get_contents($file);

        $result = self::$db->import($file, "root", "root");

        $this->assertIsArray($result);
    }

    public function testImportWithWrongCredentials(): void
    {
        $file = __DIR__ . "/../../assets/import.surql";
        $file = file_get_contents($file);

        try {
            $result = self::$db->import($file, "root", "wrong");
        } catch (SurrealException $e) {
            $this->assertInstanceOf(SurrealException::class, $e);
        } catch (AuthException $e) {
            $this->assertInstanceOf(AuthException::class, $e);
        }
    }

    public static function tearDownAfterClass(): void
    {
        self::$db->close();
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}