<?php

namespace protocol\websocket;

use Exception;
use PHPUnit\Framework\TestCase;
use Surreal\SurrealWebsocket;

class AuthTest extends TestCase
{
    private static SurrealWebsocket $db;

    /**
     * @throws Exception
     */
    public static function setUpBeforeClass(): void
    {
        self::$db = new SurrealWebsocket(
            host: "ws://127.0.0.1:8000/rpc",
            target: ["namespace" => "test", "database" => "test"]
        );

        self::assertTrue(self::$db->isConnected());

        $token = self::$db->signin([
            "user" => "root",
            "pass" => "root"
        ]);

        self::assertIsString($token);
        self::$db->authenticate($token);

        parent::setUpBeforeClass();
    }

    /**
     * @throws Exception
     */
    public function testScopeAuth(): void
    {
        $token = self::$db->signup([
            "email" => "mario",
            "password" => "supermario",
            "ns" => "test",
            "db" => "test",
            "sc" => "user"
        ]);

        self::assertIsString($token);

        $token = self::$db->signin([
            "email" => "mario",
            "password" => "supermario",
            "ns" => "test",
            "db" => "test",
            "sc" => "user"
        ]);

        self::assertIsString($token);
    }

    public static function tearDownAfterClass(): void
    {
        self::$db->close();

        $connected = self::$db->isConnected();
        self::assertFalse($connected);

        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}