<?php

namespace protocol\websocket;

use Exception;
use PHPUnit\Framework\TestCase;
use Surreal\SurrealWebsocket;

class AuthTest extends TestCase
{
    private static SurrealWebsocket $db;

    /**
     * @throws Exception
     */
    public static function setUpBeforeClass(): void
    {
        self::$db = new SurrealWebsocket(
            host: "ws://127.0.0.1:8000/rpc",
            target: ["namespace" => "test", "database" => "test"]
        );

        self::assertTrue(self::$db->isConnected());

        parent::setUpBeforeClass();
    }

    /**
     * @throws Exception
     */
    public function testDatabaseAuth(): void
    {
        self::$db->signup([
            "user" => "beau",
            "pass" => "123456",
            "ns" => "test",
            "db" => "test"
        ]);

        self::$db->signin([
            "user" => "beau",
            "pass" => "123456",
            "ns" => "test",
            "db" => "test"
        ]);
    }

    public static function tearDownAfterClass(): void
    {
        self::$db->close();

        $connected = self::$db->isConnected();
        self::assertFalse($connected);

        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}