<?php

namespace protocol\websocket;

use PHPUnit\Framework\TestCase;
use Surreal\SurrealWebsocket;

class AuthTest extends TestCase
{
    private static SurrealWebsocket $db;

    public static function setUpBeforeClass(): void
    {
        self::$db = new SurrealWebsocket(
            host: "ws://localhost:8000/rpc",
            target: ["namespace" => "test", "database" => "test"]
        );

        self::assertTrue(self::$db->isConnected());

        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    public static function tearDownAfterClass(): void
    {
        self::$db->close();

        $connected = self::$db->isConnected();
        self::assertFalse($connected);

        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}