<?php

namespace protocol\websocket;

use Exception;
use PHPUnit\Framework\TestCase;
use Surreal\SurrealWebsocket;

class BasicTest extends TestCase
{
    private static SurrealWebsocket $db;

    /**
     * @throws Exception
     */
    public static function setUpBeforeClass(): void
    {
        self::$db = new SurrealWebsocket(
            host: "ws://localhost:8000/rpc",
            target: ["namespace" => "test", "database" => "test"]
        );

        parent::setUpBeforeClass();
    }

    public function testConnection(): void
    {
        $connected = self::$db->isConnected();
        $this->assertTrue($connected, "The websocket is not connected");
    }

    /**
     * @throws Exception
     */
    public function testUse(): void
    {
        self::$db->use(["namespace" => "test", "database" => "test"]);
        $person = self::$db->select("person:beau");

        var_dump($person);
    }

    public static function tearDownAfterClass(): void
    {
        self::$db->close();

        $connected = self::$db->isConnected();
        self::assertFalse($connected);

        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}